In [20]:
import numpy as np
import pandas as pd
import importlib
import model
from keras.datasets import mnist

In [21]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [22]:
X_train = X_train.reshape((X_train.shape[0], 28*28)).astype('float32').T
X_test = X_test.reshape((X_test.shape[0], 28*28)).astype('float32').T

X_train = X_train / 255
X_test = X_test / 255

In [23]:
importlib.reload(model)
from model import NeuralNetwork

model1 = NeuralNetwork()
model1.fit(X_train, y_train)

[3 9 3 ... 3 9 3] [5 0 4 ... 5 6 8]
Accuracy for iteration 0: 0.12375
[3 0 4 ... 7 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 100: 0.6437
[3 0 4 ... 7 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 200: 0.7965833333333333
[3 0 4 ... 5 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 300: 0.8593666666666666
[3 0 4 ... 5 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 400: 0.8794166666666666
[3 0 4 ... 5 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 500: 0.8905
[3 0 4 ... 5 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 600: 0.8974833333333333
[3 0 4 ... 5 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 700: 0.90185
[3 0 4 ... 5 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 800: 0.9048833333333334
[3 0 4 ... 5 6 8] [5 0 4 ... 5 6 8]
Accuracy for iteration 900: 0.90715


In [24]:
y_pred = model1.predict(X_test)

In [25]:
model1.accuracy(y_pred, y_test)

[7 2 1 ... 4 5 6] [7 2 1 ... 4 5 6]


0.9124